;;; ewal-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from cc.el

(register-definition-prefixes "cc" '("ewal-" "insert-warning-face"))


;;; Generated autoloads from ewal.el

(autoload 'ewal-load-colors "ewal" "\
Load colors from JSON-FILE or fallback to built-in palettes.

When JSON-FILE is nil, use `ewal-json-file`.

With FORCE non-nil, reload even when the selected source has not changed.

Return the resulting `ewal-base-palette` alist.  On any error, log a message
and fall back to built-in palettes.

(fn &optional JSON-FILE FORCE)")
(autoload 'ewal-get-color "ewal" "\
Retrieve COLOR from the `ewal-base-palette`, optionally adjusting SHADE.

COLOR is a symbol like `background`, `foreground`, `red`, etc.

SHADE is a signed integer indicating steps; each step is
`ewal-shade-percent-difference` percent, unless SHADE-PERCENT-DIFFERENCE
is provided.

Return a hex color string (e.g. \"#1a1b26\") or nil if COLOR is unknown.

(fn COLOR &optional SHADE SHADE-PERCENT-DIFFERENCE)")
(register-definition-prefixes "ewal" '("ewal-"))


;;; Generated autoloads from ewal-color-utils.el

(register-definition-prefixes "ewal-color-utils" '("ewal-color-"))


;;; Generated autoloads from ewal-palette-transient.el

(autoload 'ewal-palettes-menu "ewal-palette-transient" "\
Browse and preview loaded Ewal palettes.

(fn)" t)


;;; Generated autoloads from ewal-palette-utils.el

(autoload 'ewal-load-palette "ewal-palette-utils" "\
Load a palette from JSON FILE-PATH.

Return an alist with at least `special` and `colors` keys, or nil
if FILE-PATH is not readable.

(fn FILE-PATH)")
(autoload 'ewal-save-palette "ewal-palette-utils" "\
Save PALETTE (alist) to FILE-PATH as JSON.

(fn PALETTE FILE-PATH)")
(autoload 'ewal-audit-palettes-contrast "ewal-palette-utils" "\
Audit all palette JSON files in DIR and rank worst contrast first.

Use MIN-CONTRAST as the warning threshold.  Return sorted audit entries.

(fn DIR &optional MIN-CONTRAST)" t)
(autoload 'ewal-audit-palettes-contrast-batch "ewal-palette-utils" "\
Batch-friendly contrast audit for palette JSON files in DIR.

Use MIN-CONTRAST as the warning threshold.  Print a ranked report, worst
contrast first, to stdout and return the sorted entries.

(fn &optional DIR MIN-CONTRAST)")
(autoload 'ewal-print-palette-buffer "ewal-palette-utils" "\
Print PALETTE into a preview buffer with colored blocks.

(fn PALETTE)")
(autoload 'ewal-print-palette-ansi "ewal-palette-utils" "\
Print PALETTE colors as ANSI escape codes to *Messages*.

(fn PALETTE)")
(autoload 'ewal-load-palettes-from-directory "ewal-palette-utils" "\
Load all palette JSON files in DIR into `ewal-palettes`.

`ewal-palettes` becomes a list of (PALETTE . FILENAME) pairs.

(fn DIR)")
(autoload 'ewal-save-palettes "ewal-palette-utils" "\
Save PALETTES (alist of (PALETTE . FILE)) to their FILEs.

(fn PALETTES)")
(autoload 'ewal-palettes-transient "ewal-palette-utils" "\
Invoke transient menu for browsing palettes." t)
(register-definition-prefixes "ewal-palette-utils" '("ewal-"))


;;; Generated autoloads from ewal-theme-contrast-check.el

(autoload 'ewal-check-autocorrect "ewal-theme-contrast-check" "\
Build contrast autocorrections for THEME.

Checks THEME for faces below TRIGGER-RATIO (default 2.0).  Tries
alternative foreground/background colors from `ewal-base-palette`
plus black/white, and returns replacements aiming for TARGET-RATIO.

With APPLY-FIXES non-nil, apply the suggested changes to faces.

(fn &optional THEME TRIGGER-RATIO TARGET-RATIO APPLY-FIXES)" t)
(autoload 'ewal-check-and-fix-theme "ewal-theme-contrast-check" "\
Check THEME for contrast issues and interactively offer fixes.

(fn THEME)" t)
(autoload 'ewal-check-current-theme-contrast "ewal-theme-contrast-check" "\
Check contrast for the currently enabled theme.

With prefix arg MIN-CONTRAST, use that ratio instead of the
default 4.5.  PREVIEW-LIMIT controls how many entries to print in
the message preview.

(fn &optional MIN-CONTRAST PREVIEW-LIMIT)" t)
(autoload 'ewal-check-contrast-panel "ewal-theme-contrast-check" "\
Open the optional Transient contrast workflow panel." t)
(register-definition-prefixes "ewal-theme-contrast-check" '("ewal-"))


;;; Generated autoloads from ewal-theme-contrast-panel.el

(autoload 'ewal-theme-contrast-panel "ewal-theme-contrast-panel" "\
Inspect and repair theme contrast.

(fn)" t)


;;; Generated autoloads from ewal-uncustomized-faces.el

(autoload 'ewal-process-uncustomized-faces-interactive "ewal-uncustomized-faces" "\
Prompt for a library and palette, then use THEME-FACES and append to FILE.

(fn THEME-FACES FILE)" t)
(register-definition-prefixes "ewal-uncustomized-faces" '("ewal-"))


;;; Generated autoloads from uncustomized-faces.el

(autoload 'ewal-insert-uncustomized-faces-interactive "uncustomized-faces" "\
Prompt for a loaded library and append its missing THEME-FACES to FILE.

(fn THEME-FACES FILE)" t)
(register-definition-prefixes "uncustomized-faces" '("ewal-"))


;;; Generated autoloads from update-1.el

(autoload 'ewal-spacemacs-themes-get-colors "update-1" "\
Get colors for `spacemacs-theme'.

If BORDERS is non-nil, include border settings in the resulting
alist stored in `ewal-spacemacs-themes-colors'.

(fn &optional BORDERS)")
(register-definition-prefixes "update-1" '("ewal-spacemacs-themes-"))


;;; Generated autoloads from update-2.el

(autoload 'ewal-spacemacs-themes-get-colors "update-2" "\
Get colors for `spacemacs-theme'.
If BORDERS is non-nil, includes border settings.

(fn &optional BORDERS)")
(register-definition-prefixes "update-2" '("ewal-spacemacs-themes-"))

;;; End of scraped data

(provide 'ewal-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; ewal-autoloads.el ends here
