;;; ewal-spacemacs-themes.el --- Ride the rainbow spaceship -*- lexical-binding: t; -*-

;; Package-Requires: ((emacs "25") (ewal "0.3") (spacemacs-theme "0.2.0"))

;;; Commentary:
;;
;; Spacemacs-theme integration for `ewal`:
;;   - build a `spacemacs-theme` color table from `ewal`
;;   - provide helpers for modernizing / reloading themes

;;; Code:

(require 'cl-lib)
(require 'ewal)
(require 'ewal-color-utils)
(require 'ewal-palette-utils)
(require 'ewal-theme-contrast-check)
(require 'color)

(defvar ewal-spacemacs-themes-colors nil
  "`spacemacs-theme' compatible colors extracted from current `ewal` theme.")

(defcustom ewal-spacemacs-themes-min-contrast 4.5
  "Minimum contrast for text colors generated by the Spacemacs adaptor."
  :type 'number
  :group 'ewal)

(defcustom ewal-spacemacs-themes-min-ui-contrast 3.0
  "Minimum contrast for comments, borders, cursors, and UI accents."
  :type 'number
  :group 'ewal)

(defconst ewal-spacemacs-themes--text-roles
  '(base comment red green cyan yellow blue magenta)
  "Palette roles intended to render text on `bg1'.")

(defconst ewal-spacemacs-themes--ui-roles
  '(base-dim border highlight act2)
  "Palette roles that require non-text UI contrast against `bg1'.")

(defun ewal-spacemacs-themes--palette-candidates ()
  "Return all concrete colors from the current Ewal palette."
  (ewal-palette-color-values ewal-base-palette))

(defun ewal-spacemacs-themes--safe (foreground background minimum)
  "Return FOREGROUND adjusted to meet MINIMUM contrast on BACKGROUND."
  (ewal-color-ensure-contrast
   foreground background minimum
   (ewal-spacemacs-themes--palette-candidates)))

(defun ewal-spacemacs-themes--generate-colors (&optional borders)
  "Generate `spacemacs-theme` colorscheme from `ewal` palette.

If BORDERS is non-nil, use `ewal-primary-accent-color` for borders."
  (ewal-load-colors)
  (let* ((bg1 (ewal-get-color 'background 0))
         (bg2 (ewal-get-color 'background -2))
         (bg3 (ewal-get-color 'background -3))
         (bg4 (ewal-get-color 'background -4))
         (act1 (ewal-get-color 'background -3))
         (act2 (ewal-spacemacs-themes--safe
                (ewal-get-color ewal-primary-accent-color 0)
                bg1 ewal-spacemacs-themes-min-ui-contrast))
         (base (ewal-spacemacs-themes--safe
                (ewal-get-color 'foreground 0)
                bg1 ewal-spacemacs-themes-min-contrast))
         (base-dim (ewal-spacemacs-themes--safe
                    (ewal-get-color 'foreground -4)
                    bg1 ewal-spacemacs-themes-min-ui-contrast))
         (comment (ewal-spacemacs-themes--safe
                   (ewal-get-color 'comment 0)
                   bg1 ewal-spacemacs-themes-min-contrast))
         (border (ewal-spacemacs-themes--safe
                  (ewal-get-color
                   (if borders ewal-primary-accent-color 'foreground) 0)
                  bg1 ewal-spacemacs-themes-min-ui-contrast))
         (highlight (ewal-spacemacs-themes--safe
                     (ewal-get-color 'highlight 0)
                     bg1 ewal-spacemacs-themes-min-ui-contrast))
         (red (ewal-spacemacs-themes--safe
               (ewal-get-color 'red 0) bg1 ewal-spacemacs-themes-min-contrast))
         (green (ewal-spacemacs-themes--safe
                 (ewal-get-color 'green 0) bg1 ewal-spacemacs-themes-min-contrast))
         (cyan (ewal-spacemacs-themes--safe
                (ewal-get-color 'cyan 0) bg1 ewal-spacemacs-themes-min-contrast))
         (yellow (ewal-spacemacs-themes--safe
                  (ewal-get-color 'yellow 0) bg1 ewal-spacemacs-themes-min-contrast))
         (blue (ewal-spacemacs-themes--safe
                (ewal-get-color 'blue 0) bg1 ewal-spacemacs-themes-min-contrast))
         (magenta (ewal-spacemacs-themes--safe
                   (ewal-get-color 'magenta 0) bg1 ewal-spacemacs-themes-min-contrast)))
    `((bg1 . ,bg1)
       (bg2 . ,bg2)
       (bg3 . ,bg3)
       (bg4 . ,bg4)
       (act1 . ,act1)
       (act2 . ,act2)
       (base . ,base)
       (base-dim . ,base-dim)
       (comment . ,comment)
       (border . ,border)
       (highlight . ,highlight)
       (red . ,red)
       (green . ,green)
       (cyan . ,cyan)
       (yellow . ,yellow)
       (blue . ,blue)
       (magenta . ,magenta))))

;;;###autoload
(cl-defun ewal-spacemacs-themes-get-colors (&optional borders)
  "Get colors for `spacemacs-theme` from `ewal`.

If BORDERS is non-nil, `border` uses `ewal-primary-accent-color`."
  (setq ewal-spacemacs-themes-colors
    (ewal-spacemacs-themes--generate-colors borders))
  ewal-spacemacs-themes-colors)

(defun ewal-spacemacs-themes-check-contrast ()
  "Check contrast for all entries in `ewal-spacemacs-themes-colors`.

Return a list of (NAME COLOR RATIO) for low-contrast colors."
  (let ((background (alist-get 'bg1 ewal-spacemacs-themes-colors))
        warnings)
    (dolist (name (append ewal-spacemacs-themes--text-roles
                          ewal-spacemacs-themes--ui-roles))
      (let* ((color (alist-get name ewal-spacemacs-themes-colors))
             (minimum (if (memq name ewal-spacemacs-themes--text-roles)
                          ewal-spacemacs-themes-min-contrast
                        ewal-spacemacs-themes-min-ui-contrast))
             (ratio (and color background
                         (ewal-theme-contrast-ratio color background))))
        (when (or (null ratio)
                  (ewal-color-equal-p color background)
                  (< ratio minimum))
          (push (list name color ratio minimum) warnings))))
    (nreverse warnings)))

(defun ewal-spacemacs-themes-fix-contrast ()
  "Interactively fix contrast issues in `ewal-spacemacs-themes-colors`."
  (interactive)
  (let ((warnings (ewal-spacemacs-themes-check-contrast)))
    (if (not warnings)
      (message "All colors have acceptable contrast.")
      (dolist (warning warnings)
        (let* ((name (nth 0 warning))
               (color (nth 1 warning))
               (ratio (nth 2 warning))
               (minimum (nth 3 warning))
               (background (alist-get 'bg1 ewal-spacemacs-themes-colors)))
          (when (yes-or-no-p
                 (format "Fix color '%s' (%s)? "
                         name (if ratio (format "%.2f" ratio) "invalid")))
            (let ((new (ewal-spacemacs-themes--safe
                        color background minimum)))
              (setf (alist-get name ewal-spacemacs-themes-colors) new)
              (message "Adjusted '%s' to %s" name new))))))))

(defun ewal-spacemacs-themes-modernize-theme (theme)
  "Modernize `spacemacs-theme` THEME with `ewal-spacemacs-themes-colors`."
  (let ((class '((class color) (min-colors 89))))
    (custom-theme-set-faces
      theme
      `(default ((,class (:background ,(alist-get 'bg1 ewal-spacemacs-themes-colors)
                           :foreground ,(alist-get 'base ewal-spacemacs-themes-colors)))))
      `(cursor ((,class (:background ,(alist-get 'highlight ewal-spacemacs-themes-colors)))))
      `(line-number ((,class (:foreground ,(ewal-spacemacs-themes--safe
                                             (alist-get 'comment ewal-spacemacs-themes-colors)
                                             (alist-get 'bg2 ewal-spacemacs-themes-colors)
                                             ewal-spacemacs-themes-min-ui-contrast)
                               :background ,(alist-get 'bg2 ewal-spacemacs-themes-colors)))))
      `(region ((,class (:background ,(alist-get 'bg3 ewal-spacemacs-themes-colors))))))))

;;;###autoload
(defun ewal-spacemacs-themes-reload ()
  "Reload the Spacemacs dark theme with the current `ewal` palette."
  (interactive)
  (ewal-spacemacs-themes-get-colors)
  (ewal-spacemacs-themes-modernize-theme 'spacemacs-dark))

(provide 'ewal-spacemacs-themes)
;;; ewal-spacemacs-themes.el ends here
